CREATE TABLE DEPARTAMENTO
(CD NUMBER(2) PRIMARY KEY,
D VARCHAR2(60));

CREATE TABLE AREA
(CAR NUMBER(3) PRIMARY KEY,
AR VARCHAR2(60),
CD NUMBER(2) REFERENCES DEPARTAMENTO ON DELETE CASCADE);

CREATE TABLE PROFESOR
(DNI NUMBER(8) PRIMARY KEY,
P VARCHAR2(60),
CAR NUMBER(3),
CAT VARCHAR2(5),
FOREIGN KEY (CAR) REFERENCES AREA ON DELETE SET NULL);

CREATE TABLE ASIGNATURA
(CAS NUMBER(3) PRIMARY KEY,
A VARCHAR2(50) NOT NULL,
T CHAR(4) NOT NULL,
CUR NUMBER(1) CHECK (CUR BETWEEN 1 AND 5),
CAR NUMBER(3) REFERENCES AREA ON DELETE SET NULL,
CT NUMBER(3,1) DEFAULT 0.0,
CP NUMBER(3,1) DEFAULT 0.0,
CL NUMBER(3,1) DEFAULT 0.0);

CREATE TABLE PLAN_DOCENTE
(DNI NUMBER(8),
CAS NUMBER(3),
CTA NUMBER(3,1)DEFAULT 0.0,
CPA NUMBER(3,1)DEFAULT 0.0,
CLA NUMBER(3,1)DEFAULT 0.0,
FI DATE DEFAULT SYSDATE,
FF DATE,
PRIMARY KEY (DNI, CAS, FI),
FOREIGN KEY (CAS) REFERENCES ASIGNATURA ON DELETE CASCADE,
FOREIGN KEY (DNI) REFERENCES PROFESOR ON DELETE CASCADE,
CONSTRAINT PD_CK1 CHECK (CTA + CPA + CLA > 0.0),
CONSTRAINT PD_CK2 CHECK (FF >= FI));



