INSERT INTO DEPARTAMENTO
VALUES(1,'ANALISIS MATEMATICO');
INSERT INTO DEPARTAMENTO
VALUES(2, 'ASTROFISICA');
INSERT INTO DEPARTAMENTO
VALUES(3, 'ESTADISTICA, INVESTIGACION OPERATIVA Y COMPUTACION');
INSERT INTO DEPARTAMENTO
VALUES(4, 'MATEMATICA FUNDAMENTAL');
