INSERT INTO AREA
VALUES(1, 'ALGEBRA', 4);
INSERT INTO AREA
VALUES(2, 'ANALISIS MATEMATICO', 1);
INSERT INTO AREA
VALUES(3, 'ASTRONOMIA Y ASTROFISICA', 2);
INSERT INTO AREA
VALUES(4, 'CIENCIAS DE LA COMPUTACION E INTELIGENCIA ARTIFICIAL', 3);
INSERT INTO AREA
VALUES(5, 'DIDACTICA DE LA MATEMATICA', 1);
INSERT INTO AREA
VALUES(6, 'ESTADISTICA E INVESTIGACION OPERATIVA', 3);
INSERT INTO AREA
VALUES(7, 'LENGUAJES Y SISTEMAS INFORMATICOS', 3);
INSERT INTO AREA
VALUES(8, 'MATEMATICA APLICADA', 1);
