INSERT INTO ASIGNATURA (CAS, A, T, CUR, CAR, CT, CP, CL)
VALUES (1, 'BASES DE DATOS', 'GII', 3, 7, 3, 1.5, 1.5);

INSERT INTO ASIGNATURA (CAS, A, T, CUR, CAR, CT, CP, CL)
VALUES (2, 'INTELIGENCIA ARTIFICIAL', 'GII', 3, 4, 1.5, 1.5, 3);

INSERT INTO ASIGNATURA (CAS, A, T, CUR, CAR, CT, CP, CL)
VALUES (3, 'ALMACENES DE DATOS', 'MII', 1, 7, 1.5, 0, 1.5);

INSERT INTO ASIGNATURA (CAS, A, T, CUR, CAR, CT, CP, CL)
VALUES (4, 'MINERIA DE DATOS', 'MII', 1, 7, 1.5, 0, 1.5);

INSERT INTO ASIGNATURA (CAS, A, T, CUR, CAR, CT, CP, CL)
VALUES (5, 'INFORMATICA BASICA', 'GII', 1, 7, 3, 1.5, 1.5);

INSERT INTO ASIGNATURA (CAS, A, T, CUR, CAR, CT, CP, CL)
VALUES (6, 'ALGEBRA', 'GII', 1, 1, 3, 3, 0);

INSERT INTO ASIGNATURA (CAS, A, T, CUR, CAR, CT, CP, CL)
VALUES (7, 'CALCULO', 'GII', 1, 8, 3, 3, 0);

INSERT INTO ASIGNATURA (CAS, A, T, CUR, CAR, CT, CP, CL)
VALUES (8, 'OPTIMIZACION', 'GII', 1, 6, 3, 1.5, 1.5);

INSERT INTO ASIGNATURA (CAS, A, T, CUR, CAR, CT, CP, CL)
VALUES (9, 'GESTION DE RIESGOS', 'GII', 3, 4, 3, 0, 3);

INSERT INTO ASIGNATURA (CAS, A, T, CUR, CAR, CT, CP, CL)
VALUES (10, 'ASTRONOMIA', 'GF', 2, 3, 3, 1.5, 1.5);

INSERT INTO ASIGNATURA (CAS, A, T, CUR, CAR, CT, CP, CL)
VALUES (11, 'DIDACTICA DE LA MATEMATICA', 'GM', 2, 5, 6, 0, 0);

INSERT INTO ASIGNATURA (CAS, A, T, CUR, CAR, CT, CP, CL)
VALUES (12, 'ANALISIS COMPLEJO', 'GM', 4, 2, 4.5, 3, 0);

